spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
  mail:
    host: localhost
    port: 1025
    username: fanyi
    password: fanyi
    properties:
      mail:
        smtp:
            trust: "*"  # Trust all hosts for development purposes
        auth: true 
        starttls:
          enable: true
        connectiontimeout: 5000 
        timeout: 3000
        writetimeout: 5000      